pipeline {
  agent none
  stages {
    stage('backend') {
      steps {
        sh ""
      }
      agent { docker {image 'maven:3.8.1-adoptopenjdk-11'}}
    }
    stage('frontend') {
      steps {
        sh ""
      }
      agent { docker {image 'node:16-alpine'}}
    }

  }
}